# Generated by Django 5.2.5 on 2025-08-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=80)),
                ('almacenamiento_gb', models.PositiveIntegerField()),
                ('ram_gb', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagen_url', models.URLField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
