# Generated by Django 5.1.11 on 2025-08-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0002_marca_sahumerio_delete_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahumerio',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
