# Generated by Django 5.1.1 on 2025-09-05 00:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0003_alter_sahumerio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahumerio',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterModelOptions(
            name='sahumerio',
            options={'ordering': ['marca', 'nombre']},
        ),
        migrations.RemoveField(
            model_name='sahumerio',
            name='disponible',
        ),
        migrations.AddField(
            model_name='sahumerio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sahumerio',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sahumerio',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sahumerio',
            name='imagen_file',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='sahumerio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sahumerio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
