# Generated by Django 5.1.1 on 2025-12-11 03:13

import cloudinary.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-creado'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Producto visible en catálogo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, default='', help_text='Categoría del producto', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, default='', help_text='Marca del producto', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='modificado',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Última modificación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, help_text='Se genera automáticamente del nombre', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=10, help_text='Cantidad disponible'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen del producto', max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(help_text='Nombre del sahumerio', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio en pesos argentinos', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
