# Generated by Django 5.1.1 on 2025-10-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('modalidad', models.CharField(choices=[('retiro', 'Retiro en punto de entrega'), ('envio', 'Envío a domicilio')], default='retiro', max_length=10)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('medio_pago', models.CharField(choices=[('mp', 'Mercado Pago'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='mp', max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('items_json', models.TextField(default='[]')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
